//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.03 at 09:57:03 PM MDT 
//


package com.bagalee.aqs.schema.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
 

/**
 * <p>Java class for LocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:us:net:exchangenetwork:sc:1:0}LatitudeMeasure"/>
 *         &lt;element ref="{urn:us:net:exchangenetwork:sc:1:0}LongitudeMeasure"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}VerticalMeasure"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}LocationalMetadata" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationType", namespace = "http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0", propOrder = {
    "latitudeMeasure",
    "longitudeMeasure",
    "verticalMeasure",
    "locationalMetadata"
})
public class LocationType {

    @XmlElement(name = "LatitudeMeasure", namespace = "urn:us:net:exchangenetwork:sc:1:0", required = true)
    protected String latitudeMeasure;
    @XmlElement(name = "LongitudeMeasure", namespace = "urn:us:net:exchangenetwork:sc:1:0", required = true)
    protected String longitudeMeasure;
    @XmlElement(name = "VerticalMeasure", required = true)
    protected VerticalMeasureType verticalMeasure;
    @XmlElement(name = "LocationalMetadata")
    protected LocationalMetaDataType locationalMetadata;

    /**
     * Gets the value of the latitudeMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitudeMeasure() {
        return latitudeMeasure;
    }

    /**
     * Sets the value of the latitudeMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitudeMeasure(String value) {
        this.latitudeMeasure = value;
    }

    /**
     * Gets the value of the longitudeMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitudeMeasure() {
        return longitudeMeasure;
    }

    /**
     * Sets the value of the longitudeMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitudeMeasure(String value) {
        this.longitudeMeasure = value;
    }

    /**
     * Gets the value of the verticalMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link VerticalMeasureType }
     *     
     */
    public VerticalMeasureType getVerticalMeasure() {
        return verticalMeasure;
    }

    /**
     * Sets the value of the verticalMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticalMeasureType }
     *     
     */
    public void setVerticalMeasure(VerticalMeasureType value) {
        this.verticalMeasure = value;
    }

    /**
     * Gets the value of the locationalMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link LocationalMetaDataType }
     *     
     */
    public LocationalMetaDataType getLocationalMetadata() {
        return locationalMetadata;
    }

    /**
     * Sets the value of the locationalMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationalMetaDataType }
     *     
     */
    public void setLocationalMetadata(LocationalMetaDataType value) {
        this.locationalMetadata = value;
    }

}
