//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.03 at 09:57:03 PM MDT 
//


package com.bagalee.aqs.schema.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationalMetaDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationalMetaDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}HorizontalDatumName"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}VerticalDatumName"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}HorizontalAccuracyMeasure"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}VerticalAccuracyMeasure"/>
 *         &lt;element ref="{urn:us:net:exchangenetwork:sc:1:0}SourceMapScaleNumber" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationalMetaDataType", namespace = "http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0", propOrder = {
    "horizontalDatumName",
    "verticalDatumName",
    "horizontalAccuracyMeasure",
    "verticalAccuracyMeasure",
    "sourceMapScaleNumber"
})
public class LocationalMetaDataType {

    @XmlElement(name = "HorizontalDatumName", required = true)
    protected String horizontalDatumName;
    @XmlElement(name = "VerticalDatumName", required = true)
    protected String verticalDatumName;
    @XmlElement(name = "HorizontalAccuracyMeasure", required = true)
    protected HorizontalAccuracyMeasureType horizontalAccuracyMeasure;
    @XmlElement(name = "VerticalAccuracyMeasure", required = true)
    protected VerticalAccuracyMeasureType verticalAccuracyMeasure;
    @XmlElement(name = "SourceMapScaleNumber", namespace = "urn:us:net:exchangenetwork:sc:1:0")
    protected BigInteger sourceMapScaleNumber;

    /**
     * Gets the value of the horizontalDatumName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalDatumName() {
        return horizontalDatumName;
    }

    /**
     * Sets the value of the horizontalDatumName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalDatumName(String value) {
        this.horizontalDatumName = value;
    }

    /**
     * Gets the value of the verticalDatumName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalDatumName() {
        return verticalDatumName;
    }

    /**
     * Sets the value of the verticalDatumName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalDatumName(String value) {
        this.verticalDatumName = value;
    }

    /**
     * Gets the value of the horizontalAccuracyMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link HorizontalAccuracyMeasureType }
     *     
     */
    public HorizontalAccuracyMeasureType getHorizontalAccuracyMeasure() {
        return horizontalAccuracyMeasure;
    }

    /**
     * Sets the value of the horizontalAccuracyMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link HorizontalAccuracyMeasureType }
     *     
     */
    public void setHorizontalAccuracyMeasure(HorizontalAccuracyMeasureType value) {
        this.horizontalAccuracyMeasure = value;
    }

    /**
     * Gets the value of the verticalAccuracyMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link VerticalAccuracyMeasureType }
     *     
     */
    public VerticalAccuracyMeasureType getVerticalAccuracyMeasure() {
        return verticalAccuracyMeasure;
    }

    /**
     * Sets the value of the verticalAccuracyMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticalAccuracyMeasureType }
     *     
     */
    public void setVerticalAccuracyMeasure(VerticalAccuracyMeasureType value) {
        this.verticalAccuracyMeasure = value;
    }

    /**
     * Gets the value of the sourceMapScaleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSourceMapScaleNumber() {
        return sourceMapScaleNumber;
    }

    /**
     * Sets the value of the sourceMapScaleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSourceMapScaleNumber(BigInteger value) {
        this.sourceMapScaleNumber = value;
    }

}
