//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.03 at 09:57:03 PM MDT 
//


package com.bagalee.aqs.schema.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeasurementMetadataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasurementMetadataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}MinimumDetectableLimit"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}MeasurementUncertainty"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}QualifierDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasurementMetadataType", namespace = "http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0", propOrder = {
    "minimumDetectableLimit",
    "measurementUncertainty",
    "qualifierDescription"
})
public class MeasurementMetadataType {

    @XmlElement(name = "MinimumDetectableLimit", required = true)
    protected String minimumDetectableLimit;
    @XmlElement(name = "MeasurementUncertainty")
    protected double measurementUncertainty;
    @XmlElement(name = "QualifierDescription")
    protected String qualifierDescription;

    /**
     * Gets the value of the minimumDetectableLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumDetectableLimit() {
        return minimumDetectableLimit;
    }

    /**
     * Sets the value of the minimumDetectableLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumDetectableLimit(String value) {
        this.minimumDetectableLimit = value;
    }

    /**
     * Gets the value of the measurementUncertainty property.
     * 
     */
    public double getMeasurementUncertainty() {
        return measurementUncertainty;
    }

    /**
     * Sets the value of the measurementUncertainty property.
     * 
     */
    public void setMeasurementUncertainty(double value) {
        this.measurementUncertainty = value;
    }

    /**
     * Gets the value of the qualifierDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifierDescription() {
        return qualifierDescription;
    }

    /**
     * Sets the value of the qualifierDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifierDescription(String value) {
        this.qualifierDescription = value;
    }

}
