//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.03 at 09:57:03 PM MDT 
//


package com.bagalee.aqs.schema.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MeasurementEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasurementEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}GeographicalLocation"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}AQSParameterDescription"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}Date"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}Time"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}TimeZone"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}StatisticName"/>
 *         &lt;element ref="{urn:us:net:exchangenetwork:sc:1:0}MeasureValue"/>
 *         &lt;element ref="{urn:us:net:exchangenetwork:sc:1:0}MeasureUnitName"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}ObservationCount"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}DataSourceReferenceID" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}MonitorType" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}MethodDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}MeasurementMetadata" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasurementEntityType", namespace = "http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0", propOrder = {
    "geographicalLocation",
    "aqsParameterDescription",
    "date",
    "time",
    "timeZone",
    "statisticName",
    "measureValue",
    "measureUnitName",
    "observationCount",
    "dataSourceReferenceID",
    "monitorType",
    "methodDescription",
    "measurementMetadata"
})
public class MeasurementEntityType {

    @XmlElement(name = "GeographicalLocation", required = true)
    protected LocationType geographicalLocation;
    @XmlElement(name = "AQSParameterDescription", required = true)
    protected String aqsParameterDescription;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "Time", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;
    @XmlElement(name = "TimeZone", required = true)
    protected String timeZone;
    @XmlElement(name = "StatisticName", required = true)
    protected String statisticName;
    @XmlElement(name = "MeasureValue", namespace = "urn:us:net:exchangenetwork:sc:1:0", required = true)
    protected String measureValue;
    @XmlElement(name = "MeasureUnitName", namespace = "urn:us:net:exchangenetwork:sc:1:0", required = true)
    protected String measureUnitName;
    @XmlElement(name = "ObservationCount", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger observationCount;
    @XmlElement(name = "DataSourceReferenceID")
    protected String dataSourceReferenceID;
    @XmlElement(name = "MonitorType")
    protected String monitorType;
    @XmlElement(name = "MethodDescription")
    protected String methodDescription;
    @XmlElement(name = "MeasurementMetadata")
    protected MeasurementMetadataType measurementMetadata;

    /**
     * Gets the value of the geographicalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getGeographicalLocation() {
        return geographicalLocation;
    }

    /**
     * Sets the value of the geographicalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setGeographicalLocation(LocationType value) {
        this.geographicalLocation = value;
    }

    /**
     * Gets the value of the aqsParameterDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAQSParameterDescription() {
        return aqsParameterDescription;
    }

    /**
     * Sets the value of the aqsParameterDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAQSParameterDescription(String value) {
        this.aqsParameterDescription = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Name of the statistical value  being reported (e.g. raw measurement, daily mean, annual mean, and etdc.)
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatisticName() {
        return statisticName;
    }

    /**
     * Sets the value of the statisticName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatisticName(String value) {
        this.statisticName = value;
    }

    /**
     * Gets the value of the measureValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureValue() {
        return measureValue;
    }

    /**
     * Sets the value of the measureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureValue(String value) {
        this.measureValue = value;
    }

    /**
     * Gets the value of the measureUnitName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureUnitName() {
        return measureUnitName;
    }

    /**
     * Sets the value of the measureUnitName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureUnitName(String value) {
        this.measureUnitName = value;
    }

    /**
     * Count of Total Observations comprising the statistical measured value reported.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObservationCount() {
        return observationCount;
    }

    /**
     * Sets the value of the observationCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObservationCount(BigInteger value) {
        this.observationCount = value;
    }

    /**
     * Gets the value of the dataSourceReferenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceReferenceID() {
        return dataSourceReferenceID;
    }

    /**
     * Sets the value of the dataSourceReferenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceReferenceID(String value) {
        this.dataSourceReferenceID = value;
    }

    /**
     * Gets the value of the monitorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonitorType() {
        return monitorType;
    }

    /**
     * Sets the value of the monitorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonitorType(String value) {
        this.monitorType = value;
    }

    /**
     * Gets the value of the methodDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodDescription() {
        return methodDescription;
    }

    /**
     * Sets the value of the methodDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodDescription(String value) {
        this.methodDescription = value;
    }

    /**
     * Gets the value of the measurementMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementMetadataType }
     *     
     */
    public MeasurementMetadataType getMeasurementMetadata() {
        return measurementMetadata;
    }

    /**
     * Sets the value of the measurementMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementMetadataType }
     *     
     */
    public void setMeasurementMetadata(MeasurementMetadataType value) {
        this.measurementMetadata = value;
    }

}
