//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.03 at 09:57:03 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:us:net:exchangenetwork:sc:1:0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bagalee.aqs.schema.jaxb;
