//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.03 at 09:57:03 PM MDT 
//


package com.bagalee.aqs.schema.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerticalAccuracyMeasureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerticalAccuracyMeasureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}AccuracyMeasureValue"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}AccuracyMeasureUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerticalAccuracyMeasureType", namespace = "http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0", propOrder = {
    "accuracyMeasureValue",
    "accuracyMeasureUnit"
})
public class VerticalAccuracyMeasureType {

    @XmlElement(name = "AccuracyMeasureValue", required = true)
    protected String accuracyMeasureValue;
    @XmlElement(name = "AccuracyMeasureUnit", required = true)
    protected String accuracyMeasureUnit;

    /**
     * Gets the value of the accuracyMeasureValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccuracyMeasureValue() {
        return accuracyMeasureValue;
    }

    /**
     * Sets the value of the accuracyMeasureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccuracyMeasureValue(String value) {
        this.accuracyMeasureValue = value;
    }

    /**
     * Gets the value of the accuracyMeasureUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccuracyMeasureUnit() {
        return accuracyMeasureUnit;
    }

    /**
     * Sets the value of the accuracyMeasureUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccuracyMeasureUnit(String value) {
        this.accuracyMeasureUnit = value;
    }

}
