//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.03 at 09:57:03 PM MDT 
//


package com.bagalee.aqs.schema.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerticalMeasureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerticalMeasureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}VerticalMeasureValue"/>
 *         &lt;element ref="{http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0}VerticalMeasureUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerticalMeasureType", namespace = "http://www.exchangenetwork.net/schema/AirQuality/GeoCodedData/1_0", propOrder = {
    "verticalMeasureValue",
    "verticalMeasureUnit"
})
public class VerticalMeasureType {

    @XmlElement(name = "VerticalMeasureValue", required = true)
    protected String verticalMeasureValue;
    @XmlElement(name = "VerticalMeasureUnit", required = true)
    protected String verticalMeasureUnit;

    /**
     * Gets the value of the verticalMeasureValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalMeasureValue() {
        return verticalMeasureValue;
    }

    /**
     * Sets the value of the verticalMeasureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalMeasureValue(String value) {
        this.verticalMeasureValue = value;
    }

    /**
     * Gets the value of the verticalMeasureUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalMeasureUnit() {
        return verticalMeasureUnit;
    }

    /**
     * Sets the value of the verticalMeasureUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalMeasureUnit(String value) {
        this.verticalMeasureUnit = value;
    }

}
